### ISSUE TITLE
Prompt for database name, user name, and password

### ISSUE THREAD

**Issue by dsubhaji** [dsubhaji/Gnome-ecosystem#1]
In the people-pre-analysis.R and repo-pre-analysis.R files, instead of hard-coding database name, user name, and password, prompt the user to enter them one by one.

**Comment by heyitsfifi** [comment]
we use .rs.askForPassword("Enter password:") in the gnome=dbConnect() statement. This will prompt the user to enter the database, user and password one by one. It will generate a pop-up for user to enter the details.

**Comment by dsubhaji** [comment]
It is accepting the user details ok. But for db name and user name, the user entries are marked out, like password. Could we have the characters for the db name and user name show as the user enters them?

**Comment by aliceyappy** [comment]
we have commited the lastest code with characters for the db name and user name show as the user enters

**Comment by dsubhaji** [comment]
Thanks!
