### ISSUE TITLE
Folder path in repo-pre-analysis.R and people-pre-analysis.R

### ISSUE THREAD

**Issue by dsubhaji** [dsubhaji/Gnome-ecosystem#3]
All the files are being written under paths like "R language/1st Project/ ..." If such paths does not exist (as will be the case in user computers) the program is throwing an error. Could you please change the code so that the output files are written in the same folder from which the code is being run?

**Comment by aliceyappy** [comment]
Instead of saving in a folder we just save the file which will save in the working directory of the user.

**Comment by dsubhaji** [comment]
Thanks!
