### ISSUE TITLE
Correlations plot - R encountered a fatal error

### ISSUE THREAD

**Issue by dsubhaji** [dsubhaji/Gnome-ecosystem#4]
I am getting a fatal error while running the correlations plot - look at the folder with this issue id in the the shared Dropbox folder; the input file is also given there.

**Comment by heyitsfifi** [comment]
Can you try to reinstall Rcpp: install.packages('Rcpp') and see it if it works? Because i tried to run the app and it works for me.

**Comment by dsubhaji** [comment]
Done! Works now. Thanks!
