### ISSUE TITLE
repo-pre-analysis.R - Option 3

### ISSUE THREAD

**Issue by dsubhaji** [dsubhaji/Gnome-ecosystem#5]
I am getting the following output for repo-pre-analysis.R - Option 3. The authorsHistogram.png file is being generated, but not the corresponding boxplot.

---

Please select from following options: 

0: Generate csv file

1: Number of Commits 

2: Number of Committers

3: Number of Authors

4: Number of Files

5: Exit program3
[1] "3"
Saving 7.74 x 3.83 in image
stat_bin: binwidth defaulted to range/30. Use 'binwidth = x' to adjust this.
Saving 7.74 x 3.83 in image
Error in grDevices::png(..., width = width, height = height, res = dpi,  : 
  unable to start png() device
In addition: Warning messages:
1: In grDevices::png(..., width = width, height = height, res = dpi,  :
  unable to open file 'R language/1st Project/graphs/repo-pre-analysis/Authors/authorsBoxPlot.png' for writing
2: In grDevices::png(..., width = width, height = height, res = dpi,  :
  opening device failed

**Comment by aliceyappy** [comment]
Siti have replaced the file

**Comment by dsubhaji** [comment]
Thanks!
