### ISSUE TITLE
people-pre-analysis.R - Error in option 4

### ISSUE THREAD

**Issue by dsubhaji** [dsubhaji/Gnome-ecosystem#6]
I am having the following error - Neither histogram nor boxplot are being generated

---

Select from following options:
  0: Generate csv file

  1: Number of committers

  2: Number of authors

  3: Number of repo each person commits to

  4: Number of repo: authored commits to

  5: Exit 4
[1] "4"
Saving 7.74 x 3.83 in image
Error in grDevices::png(..., width = width, height = height, res = dpi,  : 
  unable to start png() device
In addition: Warning messages:
1: In grDevices::png(..., width = width, height = height, res = dpi,  :
  unable to open file 'R language/1st Project/graphs/people-pre-analysis/RepoOfAuthors/pRepoAuthorHist.png' for writing
2: In grDevices::png(..., width = width, height = height, res = dpi,  :
  opening device failed

**Comment by heyitsfifi** [comment]
I have committed the latest code. Sorry forgot to remove the path earlier.

**Comment by dsubhaji** [comment]
Thanks!
